### ISSUE TITLE
Spacing in About section on index page

### ISSUE THREAD

**Issue by rchampieux** [BioDataClubKit/BioDataClubKit.github.io#6]
Hi @laderast is there a way to add a line break in the about section?  I was hoping this portion of the text - "The BioData Club Kit will help you start your own co-learning community! In addition to a website template, we’ve included a few of our most successful lessons, advice and resources for building a local co-learning club (we’ve leveraged a lot of good work from other organizations), and surveys for understanding your community’s needs and goals." - could start on a new line.  I tried to do this, but it didn't work 😸

**Comment by laderast** [comment]
If you start the string with a “|”, every newline should show up. So you can just add a couple of newlines for a new paragraph: https://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines

**Comment by laderast** [comment]
I figured it out. For double quoted strings, you need to add `\\n` to add a line break. You can see an example in `index.html` under "What is BioData club?"

**Comment by rchampieux** [comment]
Hi @laderast that didn't work.  When I looked at the site, it was just showing that code as characters and not creating the paragraph gap or line break.  I looked at the SO post and tried some other fixes, but no luck yet....though I did get the code to stop showing up as characters.  About to board my flight to DC, but will do some more work on this.

**Comment by laderast** [comment]
huh. It was working when I committed yesterday

**Comment by laderast** [comment]
@rchampieux I got this to work. The issue was that the excerpt text was getting run through the markdown processor, which was removing the line breaks. I removed this. I added line breaks with `<br>`. You can see it on the main page.

**Comment by rchampieux** [comment]
Yes! Thank you @laderast.
